import { pgTable, serial, text, timestamp, integer, pgEnum, index, boolean } from "drizzle-orm/pg-core"
import { relations } from "drizzle-orm"
import { leagues, teams } from "./leagues"
import { riders } from "./riders"
import { races } from "./races"
import { user } from "./users"

export const transferBidStatusEnum = pgEnum("transfer_bid_status", [
  "pending",
  "approved",
  "rejected",
  "cancelled"
])

export const transferBids = pgTable("transfer_bids", {
  id: serial("id").primaryKey(),
  leagueId: integer("leagueId").notNull().references(() => leagues.id, { onDelete: "cascade" }),
  teamId: integer("teamId").notNull().references(() => teams.id),
  outRiderId: integer("outRiderId").references(() => riders.id),
  inRiderId: integer("inRiderId").notNull().references(() => riders.id),
  bidAmount: integer("bidAmount").notNull().default(0),
  status: transferBidStatusEnum("status").notNull().default("pending"),
  reason: text("reason"),
  adminNote: text("adminNote"),
  submittedAt: timestamp("submittedAt", { withTimezone: true }).notNull().defaultNow(),
  resolvedAt: timestamp("resolvedAt", { withTimezone: true }),
  resolvedBy: text("resolvedBy").references(() => user.id),
}, (table) => ({
  leagueIdx: index("transfer_bids_league_idx").on(table.leagueId),
  teamIdx: index("transfer_bids_team_idx").on(table.teamId),
  statusIdx: index("transfer_bids_status_idx").on(table.status),
}))

export const transferWindows = pgTable("transfer_windows", {
  id: serial("id").primaryKey(),
  leagueId: integer("leagueId").notNull().references(() => leagues.id, { onDelete: "cascade" }),
  raceId: integer("raceId").references(() => races.id),
  maxTransfers: integer("maxTransfers"),
  opensAt: timestamp("opensAt", { withTimezone: true }).notNull(),
  closesAt: timestamp("closesAt", { withTimezone: true }).notNull(),
  windowType: text("windowType").notNull().default("waiver"), // 'waiver' | 'free_agency'
  description: text("description"),
  isAutoGenerated: boolean("isAutoGenerated").notNull().default(true),
}, (table) => ({
  leagueIdx: index("transfer_windows_league_idx").on(table.leagueId),
}))

export const transferAudit = pgTable("transfer_audit", {
  id: serial("id").primaryKey(),
  transferBidId: integer("transferBidId").notNull().references(() => transferBids.id),
  leagueId: integer("leagueId").notNull().references(() => leagues.id),
  action: text("action").notNull(),
  performedBy: text("performedBy").notNull().references(() => user.id),
  performedAt: timestamp("performedAt", { withTimezone: true }).notNull().defaultNow(),
  note: text("note"),
})

// Relations

export const transferBidsRelations = relations(transferBids, ({ one }) => ({
  league: one(leagues, {
    fields: [transferBids.leagueId],
    references: [leagues.id]
  }),
  team: one(teams, {
    fields: [transferBids.teamId],
    references: [teams.id]
  }),
  outRider: one(riders, {
    fields: [transferBids.outRiderId],
    references: [riders.id],
    relationName: "outRider"
  }),
  inRider: one(riders, {
    fields: [transferBids.inRiderId],
    references: [riders.id],
    relationName: "inRider"
  }),
  resolvedByUser: one(user, {
    fields: [transferBids.resolvedBy],
    references: [user.id]
  }),
}))

export const transferWindowsRelations = relations(transferWindows, ({ one }) => ({
  league: one(leagues, {
    fields: [transferWindows.leagueId],
    references: [leagues.id]
  }),
  race: one(races, {
    fields: [transferWindows.raceId],
    references: [races.id]
  }),
}))

export const transferAuditRelations = relations(transferAudit, ({ one }) => ({
  transferBid: one(transferBids, {
    fields: [transferAudit.transferBidId],
    references: [transferBids.id]
  }),
  league: one(leagues, {
    fields: [transferAudit.leagueId],
    references: [leagues.id]
  }),
  performedByUser: one(user, {
    fields: [transferAudit.performedBy],
    references: [user.id]
  }),
}))
