CREATE TYPE "public"."draft_status" AS ENUM('pending', 'men', 'women', 'complete', 'paused');--> statement-breakpoint
CREATE TYPE "public"."league_status" AS ENUM('setup', 'drafting', 'active', 'complete');--> statement-breakpoint
CREATE TYPE "public"."transfer_bid_status" AS ENUM('pending', 'approved', 'rejected', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."order_status" AS ENUM('pending', 'active', 'rejected', 'countered');--> statement-breakpoint
CREATE TABLE "bonus_riders" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"teamId" integer NOT NULL,
	"riderId" integer NOT NULL,
	"raceId" integer NOT NULL,
	"orderId" integer,
	"pickOrder" integer NOT NULL,
	"pickedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "draft_picks" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"teamId" integer NOT NULL,
	"riderId" integer NOT NULL,
	"pickNumber" integer NOT NULL,
	"round" integer NOT NULL,
	"gender" text NOT NULL,
	"wasAutomatic" boolean DEFAULT false NOT NULL,
	"pickedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "draft_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"status" "draft_status" DEFAULT 'pending' NOT NULL,
	"currentPickIndex" integer DEFAULT 0 NOT NULL,
	"currentTeamId" integer,
	"currentGender" text,
	"timerExpiresAt" timestamp with time zone,
	"startedAt" timestamp with time zone,
	"completedAt" timestamp with time zone,
	CONSTRAINT "draft_sessions_leagueId_unique" UNIQUE("leagueId")
);
--> statement-breakpoint
CREATE TABLE "race_results" (
	"id" serial PRIMARY KEY NOT NULL,
	"raceId" integer NOT NULL,
	"riderId" integer NOT NULL,
	"category" text DEFAULT 'finish' NOT NULL,
	"position" integer NOT NULL,
	"time" text,
	"points" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "race_results_race_rider_category_unique" UNIQUE("raceId","riderId","category"),
	CONSTRAINT "race_results_race_position_category_unique" UNIQUE("raceId","position","category")
);
--> statement-breakpoint
CREATE TABLE "result_audit" (
	"id" serial PRIMARY KEY NOT NULL,
	"raceId" integer NOT NULL,
	"resultId" integer,
	"changeType" text NOT NULL,
	"changedBy" text NOT NULL,
	"changedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"oldData" jsonb,
	"newData" jsonb,
	"reason" text
);
--> statement-breakpoint
CREATE TABLE "league_races" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"raceId" integer NOT NULL,
	"addedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leagues" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"inviteCode" text NOT NULL,
	"inviteExpiresAt" timestamp with time zone,
	"status" "league_status" DEFAULT 'setup' NOT NULL,
	"ownerId" text NOT NULL,
	"config" jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leagues_inviteCode_unique" UNIQUE("inviteCode")
);
--> statement-breakpoint
CREATE TABLE "teams" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"userId" text NOT NULL,
	"name" text NOT NULL,
	"transferBudget" integer DEFAULT 100 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transfer_audit" (
	"id" serial PRIMARY KEY NOT NULL,
	"transferBidId" integer NOT NULL,
	"leagueId" integer NOT NULL,
	"action" text NOT NULL,
	"performedBy" text NOT NULL,
	"performedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "transfer_bids" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"teamId" integer NOT NULL,
	"outRiderId" integer NOT NULL,
	"inRiderId" integer NOT NULL,
	"bidAmount" integer DEFAULT 0 NOT NULL,
	"status" "transfer_bid_status" DEFAULT 'pending' NOT NULL,
	"reason" text,
	"adminNote" text,
	"submittedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"resolvedAt" timestamp with time zone,
	"resolvedBy" text
);
--> statement-breakpoint
CREATE TABLE "transfer_windows" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"raceId" integer,
	"maxTransfers" integer,
	"opensAt" timestamp with time zone NOT NULL,
	"closesAt" timestamp with time zone NOT NULL,
	"description" text,
	"isAutoGenerated" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"teamId" integer NOT NULL,
	"raceId" integer NOT NULL,
	"orderTypeId" integer NOT NULL,
	"status" "order_status" DEFAULT 'pending' NOT NULL,
	"targetRiderId" integer,
	"targetTeamId" integer,
	"targetProTeam" text,
	"targetCountry" text,
	"orderConfig" jsonb,
	"bonusPoints" integer,
	"adminNote" text,
	"submittedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"resolvedAt" timestamp with time zone,
	"resolvedBy" text
);
--> statement-breakpoint
CREATE TABLE "race_lineups" (
	"id" serial PRIMARY KEY NOT NULL,
	"leagueId" integer NOT NULL,
	"teamId" integer NOT NULL,
	"raceId" integer NOT NULL,
	"riderId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projected_rankings" (
	"id" serial PRIMARY KEY NOT NULL,
	"rank" integer NOT NULL,
	"riderName" text NOT NULL,
	"riderId" integer,
	"team" text NOT NULL,
	"nationality" text NOT NULL,
	"projectedPoints" real NOT NULL,
	"breakdown" jsonb NOT NULL,
	"confirmedRaces" integer DEFAULT 0 NOT NULL,
	"injuryStatus" text DEFAULT 'healthy' NOT NULL,
	"injuryNote" text,
	"season" integer DEFAULT 2026 NOT NULL,
	"lastUpdated" timestamp with time zone DEFAULT now() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "riders" ADD COLUMN "draft_ranking" integer DEFAULT 9999 NOT NULL;--> statement-breakpoint
ALTER TABLE "bonus_riders" ADD CONSTRAINT "bonus_riders_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bonus_riders" ADD CONSTRAINT "bonus_riders_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bonus_riders" ADD CONSTRAINT "bonus_riders_riderId_riders_id_fk" FOREIGN KEY ("riderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bonus_riders" ADD CONSTRAINT "bonus_riders_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bonus_riders" ADD CONSTRAINT "bonus_riders_orderId_orders_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_picks" ADD CONSTRAINT "draft_picks_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_picks" ADD CONSTRAINT "draft_picks_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_picks" ADD CONSTRAINT "draft_picks_riderId_riders_id_fk" FOREIGN KEY ("riderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_sessions" ADD CONSTRAINT "draft_sessions_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "draft_sessions" ADD CONSTRAINT "draft_sessions_currentTeamId_teams_id_fk" FOREIGN KEY ("currentTeamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_results" ADD CONSTRAINT "race_results_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_results" ADD CONSTRAINT "race_results_riderId_riders_id_fk" FOREIGN KEY ("riderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_audit" ADD CONSTRAINT "result_audit_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_audit" ADD CONSTRAINT "result_audit_resultId_race_results_id_fk" FOREIGN KEY ("resultId") REFERENCES "public"."race_results"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "result_audit" ADD CONSTRAINT "result_audit_changedBy_user_id_fk" FOREIGN KEY ("changedBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_races" ADD CONSTRAINT "league_races_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "league_races" ADD CONSTRAINT "league_races_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leagues" ADD CONSTRAINT "leagues_ownerId_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "teams_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "teams" ADD CONSTRAINT "teams_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_audit" ADD CONSTRAINT "transfer_audit_transferBidId_transfer_bids_id_fk" FOREIGN KEY ("transferBidId") REFERENCES "public"."transfer_bids"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_audit" ADD CONSTRAINT "transfer_audit_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_audit" ADD CONSTRAINT "transfer_audit_performedBy_user_id_fk" FOREIGN KEY ("performedBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_bids" ADD CONSTRAINT "transfer_bids_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_bids" ADD CONSTRAINT "transfer_bids_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_bids" ADD CONSTRAINT "transfer_bids_outRiderId_riders_id_fk" FOREIGN KEY ("outRiderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_bids" ADD CONSTRAINT "transfer_bids_inRiderId_riders_id_fk" FOREIGN KEY ("inRiderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_bids" ADD CONSTRAINT "transfer_bids_resolvedBy_user_id_fk" FOREIGN KEY ("resolvedBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_windows" ADD CONSTRAINT "transfer_windows_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transfer_windows" ADD CONSTRAINT "transfer_windows_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_orderTypeId_orderTypes_id_fk" FOREIGN KEY ("orderTypeId") REFERENCES "public"."orderTypes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_targetRiderId_riders_id_fk" FOREIGN KEY ("targetRiderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_targetTeamId_teams_id_fk" FOREIGN KEY ("targetTeamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_resolvedBy_user_id_fk" FOREIGN KEY ("resolvedBy") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_lineups" ADD CONSTRAINT "race_lineups_leagueId_leagues_id_fk" FOREIGN KEY ("leagueId") REFERENCES "public"."leagues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_lineups" ADD CONSTRAINT "race_lineups_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_lineups" ADD CONSTRAINT "race_lineups_raceId_races_id_fk" FOREIGN KEY ("raceId") REFERENCES "public"."races"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "race_lineups" ADD CONSTRAINT "race_lineups_riderId_riders_id_fk" FOREIGN KEY ("riderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "projected_rankings" ADD CONSTRAINT "projected_rankings_riderId_riders_id_fk" FOREIGN KEY ("riderId") REFERENCES "public"."riders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bonus_riders_league_idx" ON "bonus_riders" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "bonus_riders_team_idx" ON "bonus_riders" USING btree ("teamId");--> statement-breakpoint
CREATE INDEX "bonus_riders_race_idx" ON "bonus_riders" USING btree ("raceId");--> statement-breakpoint
CREATE UNIQUE INDEX "bonus_riders_league_race_team_unique" ON "bonus_riders" USING btree ("leagueId","raceId","teamId");--> statement-breakpoint
CREATE UNIQUE INDEX "draft_picks_rider_league_unique" ON "draft_picks" USING btree ("leagueId","riderId");--> statement-breakpoint
CREATE UNIQUE INDEX "draft_picks_pick_number_unique" ON "draft_picks" USING btree ("leagueId","pickNumber");--> statement-breakpoint
CREATE INDEX "draft_picks_league_idx" ON "draft_picks" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "draft_picks_team_idx" ON "draft_picks" USING btree ("teamId");--> statement-breakpoint
CREATE INDEX "draft_sessions_league_idx" ON "draft_sessions" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "race_results_race_id_idx" ON "race_results" USING btree ("raceId");--> statement-breakpoint
CREATE INDEX "race_results_rider_id_idx" ON "race_results" USING btree ("riderId");--> statement-breakpoint
CREATE INDEX "race_results_category_idx" ON "race_results" USING btree ("category");--> statement-breakpoint
CREATE UNIQUE INDEX "league_races_league_race_unique" ON "league_races" USING btree ("leagueId","raceId");--> statement-breakpoint
CREATE INDEX "league_races_league_idx" ON "league_races" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "league_races_race_idx" ON "league_races" USING btree ("raceId");--> statement-breakpoint
CREATE INDEX "leagues_owner_idx" ON "leagues" USING btree ("ownerId");--> statement-breakpoint
CREATE UNIQUE INDEX "teams_league_user_unique" ON "teams" USING btree ("leagueId","userId");--> statement-breakpoint
CREATE UNIQUE INDEX "teams_league_name_unique" ON "teams" USING btree ("leagueId","name");--> statement-breakpoint
CREATE INDEX "teams_league_idx" ON "teams" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "teams_user_idx" ON "teams" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transfer_bids_league_idx" ON "transfer_bids" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "transfer_bids_team_idx" ON "transfer_bids" USING btree ("teamId");--> statement-breakpoint
CREATE INDEX "transfer_bids_status_idx" ON "transfer_bids" USING btree ("status");--> statement-breakpoint
CREATE INDEX "transfer_windows_league_idx" ON "transfer_windows" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "orders_league_idx" ON "orders" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "orders_team_idx" ON "orders" USING btree ("teamId");--> statement-breakpoint
CREATE INDEX "orders_race_idx" ON "orders" USING btree ("raceId");--> statement-breakpoint
CREATE UNIQUE INDEX "orders_team_race_unique" ON "orders" USING btree ("teamId","raceId");--> statement-breakpoint
CREATE UNIQUE INDEX "race_lineups_unique" ON "race_lineups" USING btree ("leagueId","teamId","raceId","riderId");--> statement-breakpoint
CREATE INDEX "race_lineups_league_idx" ON "race_lineups" USING btree ("leagueId");--> statement-breakpoint
CREATE INDEX "race_lineups_team_race_idx" ON "race_lineups" USING btree ("teamId","raceId");--> statement-breakpoint
CREATE INDEX "projected_rankings_rank_idx" ON "projected_rankings" USING btree ("rank");--> statement-breakpoint
CREATE INDEX "projected_rankings_season_idx" ON "projected_rankings" USING btree ("season");--> statement-breakpoint
CREATE INDEX "projected_rankings_rider_id_idx" ON "projected_rankings" USING btree ("riderId");--> statement-breakpoint
CREATE INDEX "riders_draft_rank_idx" ON "riders" USING btree ("draft_ranking");