import { Pool } from "@neondatabase/serverless"
import * as dotenv from "dotenv"
import { resolve } from "path"

// Load .env.local
dotenv.config({ path: resolve(process.cwd(), ".env.local") })

const databaseUrl = process.env.DATABASE_URL
if (!databaseUrl) {
  console.error("DATABASE_URL not set")
  process.exit(1)
}

const pool = new Pool({ connectionString: databaseUrl })

async function applyMigration() {
  const client = await pool.connect()
  try {
    // Step 1: Create enum
    console.log("Creating transfer_bid_status enum...")
    await client.query(`
      DO $$ BEGIN
        CREATE TYPE "transfer_bid_status" AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
      EXCEPTION
        WHEN duplicate_object THEN null;
      END $$;
    `)

    // Step 2: Create transfer_bids table
    console.log("Creating transfer_bids table...")
    await client.query(`
      CREATE TABLE IF NOT EXISTS "transfer_bids" (
        "id" serial PRIMARY KEY NOT NULL,
        "leagueId" integer NOT NULL REFERENCES "leagues"("id") ON DELETE CASCADE,
        "teamId" integer NOT NULL REFERENCES "teams"("id"),
        "outRiderId" integer NOT NULL REFERENCES "riders"("id"),
        "inRiderId" integer NOT NULL REFERENCES "riders"("id"),
        "status" "transfer_bid_status" NOT NULL DEFAULT 'pending',
        "reason" text,
        "adminNote" text,
        "submittedAt" timestamp with time zone NOT NULL DEFAULT now(),
        "resolvedAt" timestamp with time zone,
        "resolvedBy" text REFERENCES "user"("id")
      )
    `)

    // Step 3: Create transfer_windows table
    console.log("Creating transfer_windows table...")
    await client.query(`
      CREATE TABLE IF NOT EXISTS "transfer_windows" (
        "id" serial PRIMARY KEY NOT NULL,
        "leagueId" integer NOT NULL REFERENCES "leagues"("id") ON DELETE CASCADE,
        "raceId" integer REFERENCES "races"("id"),
        "maxTransfers" integer,
        "opensAt" timestamp with time zone NOT NULL,
        "closesAt" timestamp with time zone NOT NULL,
        "description" text,
        "isAutoGenerated" boolean NOT NULL DEFAULT true
      )
    `)

    // Step 4: Create transfer_audit table
    console.log("Creating transfer_audit table...")
    await client.query(`
      CREATE TABLE IF NOT EXISTS "transfer_audit" (
        "id" serial PRIMARY KEY NOT NULL,
        "transferBidId" integer NOT NULL REFERENCES "transfer_bids"("id"),
        "leagueId" integer NOT NULL REFERENCES "leagues"("id"),
        "action" text NOT NULL,
        "performedBy" text NOT NULL REFERENCES "user"("id"),
        "performedAt" timestamp with time zone NOT NULL DEFAULT now(),
        "note" text
      )
    `)

    // Step 5: Fix pickNumber partial index
    console.log("Fixing pickNumber partial index...")
    await client.query(`DROP INDEX IF EXISTS "draft_picks_pick_number_unique"`)
    await client.query(`
      CREATE UNIQUE INDEX "draft_picks_pick_number_unique"
      ON "draft_picks"("leagueId", "pickNumber")
      WHERE "pickNumber" >= 0
    `)

    // Step 6: Create indexes
    console.log("Creating indexes...")
    await client.query(`CREATE INDEX IF NOT EXISTS "transfer_bids_league_idx" ON "transfer_bids"("leagueId")`)
    await client.query(`CREATE INDEX IF NOT EXISTS "transfer_bids_team_idx" ON "transfer_bids"("teamId")`)
    await client.query(`CREATE INDEX IF NOT EXISTS "transfer_bids_status_idx" ON "transfer_bids"("status")`)
    await client.query(`CREATE INDEX IF NOT EXISTS "transfer_windows_league_idx" ON "transfer_windows"("leagueId")`)

    console.log("Migration applied successfully!")

    // Verify tables exist
    const result = await client.query(`
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name LIKE 'transfer%'
      ORDER BY table_name
    `)
    console.log("Transfer tables in DB:", result.rows.map((r: any) => r.table_name))

    // Verify enum exists
    const enumResult = await client.query(`
      SELECT typname FROM pg_type WHERE typname = 'transfer_bid_status'
    `)
    console.log("Enum:", enumResult.rows.map((r: any) => r.typname))

    // Verify partial index
    const indexResult = await client.query(`
      SELECT indexname, indexdef
      FROM pg_indexes
      WHERE tablename = 'draft_picks' AND indexname = 'draft_picks_pick_number_unique'
    `)
    console.log("pickNumber index:", indexResult.rows)
  } finally {
    client.release()
    await pool.end()
  }
}

applyMigration().catch((error) => {
  console.error("Migration failed:", error)
  process.exit(1)
})
